### ISSUE TITLE
Unable to sum across dimensions in the front end

### ISSUE THREAD

**Issue by cormacmlynch** [cpmodel/FTT_StandAlone#100]
For some variables, I am unable to find the sum across all regions or technologies in the front end. The 'Agg?' tickbox remains greyed out and unclickable.

![image](https://github.com/cpmodel/FTT_StandAlone/assets/122904574/2187b6ce-096a-40a4-8733-97bcc355e39d)

Oddly enough, this works fine for some other variables.

**Comment by jp-camecon** [comment]
The current version of the frontend determines if a variable is aggregatable based on the unit of the variable. If the unit is either % or has / in the unit, it is assumed the variable is a rate that cannot be aggregated. Some variables in FTT currently have odd units like FTT-Heat Capacity Additions is GW/y rather than just GW. 

A better option for this which I have used in other frontends is to have a column to flag if a variable should be aggregatable so it does not have to be inferred by the unit
