### ISSUE TITLE
Weird value of standard deviation of the O&M costs for Solar PV

### ISSUE THREAD

**Issue by QuentinLETERRIER** [cpmodel/FTT_StandAlone#117]
Hi, 
I have encountered a weird value for the solar O&M costs.
In the FTT-P-24x71_2022_S0 and FTT-P-24x71_2023_S0, in the BCET sheet,
The value of the standard deviation of the Solar PV O&M cost is higher than the O&M costs themselves, which should imply frequent negative O&M costs for solar ?
![Solar o m](https://github.com/cpmodel/FTT_StandAlone/assets/106544020/baecf9bf-54a7-40a9-94c1-1f2df5485d8c)
Anyway, if you have any explanation or tips to fix that, I am all ears.
Cheers

**Comment by pv-camecon** [comment]
That's probably due to determining the standard deviation on the basis of gobal data. Country-specific data is often too limited to determine regional SDs. 

We should probably express SDs in percentages to the average anyway as I think that the width of the deviation moves with the average (e.g. if prices increase than it makes sense to increase the uncertainty).

**Comment by Femkemilene** [comment]
I agree about expressing SD as a percentage. This can still be sector or even technology specific. If we make it technology-specific, we would compute the sample standard deviation by country, divide it by the mean of that country, and average these out. We can automate this in excel, so that we don't have to do this every update.
