### ISSUE TITLE
Resolve celib dependencies in Upload_FTT

### ISSUE THREAD

**Issue by Femkemilene** [cpmodel/FTT_StandAlone#44]
Upload_FTT.py now uses celib to find the dimensions of variables. This means that we should either rewrite this in to use Variable_Listing.xlsx, or we make celib available more widely. A compromise may be to include celib in the (private) support repo.

**Comment by PVercoulen-CE** [comment]
Perhaps it's useful to rethink how we store the FTT inputs in general. Preprocessing everything into a pickle file save a lot of loading time. However, pickle objects are a security risk (I think). It also requires any user to have some understanding of Python in order to meddle with the inputs or to create new scenarios.

If it's preferable to stick to csv files, then we can make use of the classification_titles.xlsx file as we only use the titles databank anyway.

**Comment by Femkemilene** [comment]
When you say store files in pickle files, do you mean the individual country files? It's okay if people can't read those in easily, given that the same data is more easily accessible in the Masterfiles. Keeping the Masterfiles ensures we can keep the model close to E3ME-FTT, as we use the same input.
