### ISSUE TITLE
Double check cumulative capacity historical data heat pumps

### ISSUE THREAD

**Issue by Femkemilene** [cpmodel/FTT_StandAlone#58]
At the moment, the cumulative capacities for the three types of heat pumps are very similar in the model. Cormac and me discussed that air-water heat pumps are the 'newest' type, and expected their cumulative historical capacity to be lower. We should double check this is correct in the model.

**Comment by cormacmlynch** [comment]
I decided to do some basic calculations with the EHPA data. Their sales data goes back to 1990. Assuming average heat pump capacities of 14, 12, and 4KW, their numbers give cumulative capacities of 25, 53, and 30GW for ground, air-water, and air-air respectively. Air-water has about 1/2 the sales as air-air but typical capacities much bigger. 

As these are only European numbers (and only since 1990) we could scale the split of heat pump types to the [IEAs estimate](https://www.nature.com/articles/s41560-022-01104-8#:~:text=Globally%2C%20177%20million%20heat%20pumps%20had%20been%20installed,followed%20by%20North%20America%20%2823%25%29%20and%20Europe%20%2812%25%29.) of 177 million cumulative sales. Using the same average capacities, this gives global HEWW numbers as 330, 687, 385GW for ground, air-water, and air-air. So perhaps surprisingly air-water is some way ahead. I would take this with a pinch of salt however since I suspect the IEA and EHPA definitions of air-air heat pump are quite different - EHPA are quite strict with theirs while I would guess a good chunk of the IEA's number includes reversible air-con units. I would say therefore my calculations are overestimating cumulative capacity for air-water and underestimating for air-air.

From this I would conclude that our HEWW numbers are not as wrong as I thought they might be. Nevertheless it is interesting that reports do suggest air-water is the least mature of the three and should exhibit more substantial cost declines ([see page 88 of this report](https://ens.dk/sites/ens.dk/files/Analyser/technology_data_catalogue_for_individual_heating_installations.pdf)).
